List<String> biscuitsHeaders = [
  "Date",
  "القسم",
  "الورديه",
  "عدد ساعات الورديه",
  "اجمالي توقفات الخط بالدقيقة Total line stops in Minutes",
  "نوع الصنف",
  "خط الانتاج",
  "Theoretical Speed rate (kg)/shift",
  "Unit",
  "Production  الانتاج الفعلى",
  "Total Rework اعادة تشغيل",
  "Ext Rework اعادة تشغيل",
  "Ext Scrap هالك التشكيل",
  "Scrap Reason سبب الهالك",
  "Oven Rework اعادة تشغيل",
  "Oven Scrap هالك الفرن",
  "Scrap Reason سبب الهالك",
  "Cutter Rework اعادة تشغيل",
  "Cutter Scrap الهالك",
  "Scrap Reason سبب الهالك",
  "Conv Rework اعادة تشغيل",
  "Conv Scrap الهالك",
  "Scrap Reason سبب الهالك",
  "MC1 Speed",
  "MC2 Speed",
  "MC3 Speed",
  "MC4 Speed",
  "Packing Rework اعادة تشغيل",
  "Packing Scrap هالك بسكويت منطقة التغليف",
  "Scrap Reason سبب الهالك",
  "هالك علب",
  "هالك كرتون",
  "MC1 Waste in Kg",
  "Film Waste% MC1",
  "MC2 Waste in Kg",
  "Film Waste% MC2",
  "MC3 Waste in Kg",
  "Film Waste% MC3",
  "MC4 Waste in Kg",
  "Film Waste% MC4",
  "Overweight%",
  "Scrap kg",
  "Rework%",
  "Scrap%",
  "Rate%",
  "Availability%",
  "Quality%",
  "OEE%",
  "Overweight (Kg)",
  "Rate Loss (Kg)",
  "Cartons",
  "Month",
  "Week",
  "Year"
];
List<String> waferHeaders = [
  "Date",
  "القسم",
  "الورديه",
  "عدد ساعات الورديه",
  "اجمالي توقفات الخط بالدقيقة Total line stops in Minutes",
  "نوع الصنف",
  "خط الانتاج",
  "Theoretical Speed rate (kg)/shift",
  "Unit",
  "Production  الانتاج الفعلى",
  "Total Rework اعادة تشغيل",
  "Oven Rework اعادة تشغيل",
  "Oven Scrap هالك الفرن",
  "Scrap Reason سبب الهالك",
  "Cream Rework اعادة تشغيل",
  "Cream Scrap الهالك",
  "Scrap Reason سبب الهالك",
  "Cooler Rework اعادة تشغيل",
  "Cooler Scrap الهالك",
  "Scrap Reason سبب الهالك",
  "Cutter Rework اعادة تشغيل",
  "Cutter Scrap الهالك",
  "Scrap Reason سبب الهالك",
  "MC1 Speed",
  "MC2 Speed",
  "MC3 Speed",
  "MC4 Speed",
  "Packing Rework اعادة تشغيل",
  "Packing Scrap هالك ويفر منطقة التغليف",
  "Scrap Reason سبب الهالك",
  "هالك علب",
  "هالك كرتون",
  "MC1 Waste in Kg",
  "Film Waste% MC1",
  "MC2 Waste in Kg",
  "Film Waste% MC2",
  "MC3 Waste in Kg",
  "Film Waste% MC3",
  "MC4 Waste in Kg",
  "Film Waste% MC4",
  "Overweight%",
  "Scrap kg",
  "Rework%",
  "Scrap%",
  "Rate%",
  "Availability%",
  "Quality%",
  "OEE%",
  "Overweight (Kg)",
  "Rate Loss (Kg)",
  "Cartons",
  "Month",
  "Week",
  "Year"
];
List<String> maamoulHeaders = [
  "Date",
  "القسم",
  "الورديه",
  "عدد ساعات الورديه",
  "اجمالي توقفات الخط بالدقيقة Total line stops in Minutes",
  "نوع الصنف",
  "خط الانتاج",
  "Theoretical Speed rate (kg)/shift",
  "Unit",
  "Production  الانتاج الفعلى",
  "Total Rework اعادة تشغيل",
  "Mixer Rework اعادة تشغيل",
  "Mixer Scrap الهالك",
  "Scrap Reason سبب الهالك",
  "Stamping Rework اعادة تشغيل",
  "Stamping Scrap الهالك",
  "Scrap Reason سبب الهالك",
  "Oven Rework اعادة تشغيل",
  "Oven Scrap هالك الفرن",
  "Scrap Reason سبب الهالك",
  "MC1 Speed",
  "MC2 Speed",
  "MC3 Speed",
  "MC4 Speed",
  "Packing Rework اعادة تشغيل",
  "Packing Scrap هالك معمول منطقة التغليف",
  "Scrap Reason سبب الهالك",
  "هالك علب",
  "هالك كرتون",
  "MC1 Waste in Kg",
  "Film Waste% MC1",
  "MC2 Waste in Kg",
  "Film Waste% MC2",
  "MC3 Waste in Kg",
  "Film Waste% MC3",
  "MC4 Waste in Kg",
  "Film Waste% MC4",
  "Overweight%",
  "Scrap kg",
  "Rework%",
  "Scrap%",
  "Rate%",
  "Availability%",
  "Quality%",
  "OEE%",
  "Overweight (Kg)",
  "Rate Loss (Kg)",
  "Cartons",
  "Month",
  "Week",
  "Year"
];
List<String> totalPlantHeaders = [
  "Date",
  "Plan in Kg",
  "Production in Kg",
  "Production in Cartons",
  "Total line stops in Minutes",
  "Overweight%",
  "Overweight (Kg)",
  "Scrap kg",
  "Scrap%",
  "Rework%",
  "Film Waste%",
  "Rate%",
  "Availability%",
  "Quality%",
  "OEE%",
  "RM MUV",
  "Rate Loss (Kg)",
  "Month",
  "Week",
  "Year"
];

List<String> QfsHeaders = [
  "Date",
  "Quality Incidents",
  "Food Safety Incidents",
  "CCP Failures",
  "Consumer Complaints",
  "G6 Escalation",
  "Pes",
  "Month",
  "Week",
  "Year"
];

List<String> EhsHeaders = [
  "Date",
  "First Aid Incidents",
  "Lost Time Incidents",
  "Recordable Incidents",
  "Near Miss",
  "Pre-shift risk Assessment",
  "S7 Tours",
  "Month",
  "Week",
  "Year"
];

List<String> DownTimeHeaders = [
  "Date",
  "القسم",
  "الورديه",
  "مبلغ العطل",
  "نوع الصنف",
  "خط الانتاج",
  "Type",
  "Machine",
  "isPlanned",
  "وقت بداية العطل",
  "وقت انتهاء العطل",
  "Total minutes",
  "Is there product?",
  "Root cause drop down",
  "Extra details",
  "wfCategory",
  "is Approved?",
  "Approved By",
  "is Rejected?",
  "Rejected By",
  "Reject comment",
  "technician Name",
  "Report Entry Time",
  "Month",
  "Week",
  "Year",
  "Sort Column"
];
